export const ADMIN_LOG_IN_REQUEST = "ADMIN_LOG_IN_REQUEST"
export const ADMIN_LOG_IN_SUCCESS = "ADMIN_LOG_IN_SUCCESS"
export const ADMIN_LOG_IN_FAILURE = "ADMIN_LOG_IN_FAILURE"

export const CHECK_ADMIN_LOGGED_REQUEST = "CHECK_ADMIN_LOGGED_REQUEST"
export const CHECK_ADMIN_LOGGED_SUCCESS = "CHECK_ADMIN_LOGGED_SUCCESS"
export const CHECK_ADMIN_LOGGED_FAILURE = "CHECK_ADMIN_LOGGED_FAILURE"

export const ADMIN_LOG_OUT = "ADMIN_LOG_OUT"

export const LOAD_ADMIN_ADVERTISEMENTS_SUCCESS =
    "LOAD_ADMIN_ADVERTISEMENTS_SUCCESS"
export const LOAD_ADMIN_ADVERTISEMENTS_REQUEST =
    "LOAD_ADMIN_ADVERTISEMENTS_REQUEST"
export const LOAD_ADMIN_ADVERTISEMENTS_FAILURE =
    "LOAD_ADMIN_ADVERTISEMENTS_FAILURE"

export const LOAD_VERIFICATION_STORES_REQUEST =
    "LOAD_VERIFICATION_STORES_REQUEST"
export const LOAD_VERIFICATION_STORES_SUCCESS =
    "LOAD_VERIFICATION_STORES_SUCCESS"
export const LOAD_VERIFICATION_STORES_FAILURE =
    "LOAD_VERIFICATION_STORES_FAILURE"

export const UPDATE_VERIFICATION_STORE_REQUEST =
    "UPDATE_VERIFICATION_STORE_REQUEST"
export const UPDATE_VERIFICATION_STORE_SUCCESS =
    "UPDATE_VERIFICATION_STORE_SUCCESS"
export const UPDATE_VERIFICATION_STORE_FAILURE =
    "UPDATE_VERIFICATION_STORE_FAILURE"
export const CHANGE_IS_UPDATED_VERIFICATION_STORE =
    "CHANGE_IS_UPDATED_VERIFICATION_STORE"

export const REMOVE_ADMIN_ADVERTISEMENT_REQUEST =
    "REMOVE_ADMIN_ADVERTISEMENT_REQUEST"
export const REMOVE_ADMIN_ADVERTISEMENT_SUCCESS =
    "REMOVE_ADMIN_ADVERTISEMENT_SUCCESS"
export const REMOVE_ADMIN_ADVERTISEMENT_FAILURE =
    "REMOVE_ADMIN_ADVERTISEMENT_FAILURE"
export const CHANGE_IS_REMOVED_ADVERTISEMENT = "CHANGE_IS_REMOVED_ADVERTISEMENT"
