export const ADD_ADVERTISEMENT_REQUEST = "ADD_ADVERTISEMENT_REQUEST"
export const ADD_ADVERTISEMENT_SUCCESS = "ADD_ADVERTISEMENT_SUCCESS"
export const ADD_ADVERTISEMENT_FAILURE = "ADD_ADVERTISEMENT_FAILURE"
export const CHANGE_ADDED_ADVERTISEMENT = "CHANGE_ADDED_ADVERTISEMENT"

export const UPDATE_ADVERTISEMENT_REQUEST = "UPDATE_ADVERTISEMENT_REQUEST"
export const UPDATE_ADVERTISEMENT_SUCCESS = "UPDATE_ADVERTISEMENT_SUCCESS"
export const UPDATE_ADVERTISEMENT_FAILURE = "UPDATE_ADVERTISEMENT_FAILURE"
export const CHANGE_ADVERTISEMENT_UPDATED = "CHANGE_ADVERTISEMENT_UPDATED"

export const REMOVE_ADVERTISEMENT_REQUEST = "REMOVE_ADVERTISEMENT_REQUEST"
export const REMOVE_ADVERTISEMENT_SUCCESS = "REMOVE_ADVERTISEMENT_SUCCESS"
export const REMOVE_ADVERTISEMENT_FAILURE = "REMOVE_ADVERTISEMENT_FAILURE"
export const CHANGE_ADVERTISEMENT_REMOVED = "CHANGE_ADVERTISEMENT_REMOVED"

export const LOAD_ADVERTISEMENTS_REQUEST = "LOAD_ADVERTISEMENT_REQUEST"
export const LOAD_ADVERTISEMENTS_SUCCESS = "LOAD_ADVERTISEMENT_SUCCESS"
export const LOAD_ADVERTISEMENTS_FAILURE = "LOAD_ADVERTISEMENT_FAILURE"

export const CHANGE_RADIUS = "CHANGE_RADIUS"

export const CHANGE_ADVERTISEMENT_IN_MODAL = "CHANGE_ADVERTISEMENT_IN_MODAL"
