export const SHOW_REGISTER_MODAL = "SHOW_REGISTER_MODAL"
export const HIDE_REGISTER_MODAL = "HIDE_REGISTER_MODAL"

export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL"
export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL"

export const SHOW_BIZ_REG_MODAL = "SHOW_BIZ_REG_MODAL"
export const HIDE_BIZ_REG_MODAL = "HIDE_BIZ_REG_MODAL"
