export const SHOW_REGISTER_MODAL = "SHOW_REGISTER_MODAL"
export const HIDE_REGISTER_MODAL = "HIDE_REGISTER_MODAL"

export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL"
export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL"

export const SHOW_BIZ_REG_MODAL = "SHOW_BIZ_REG_MODAL"
export const HIDE_BIZ_REG_MODAL = "HIDE_BIZ_REG_MODAL"

export const SHOW_ADVERTISEMENT_ADD_MODAL = "SHOW_ADVERTISEMENT_ADD_MODAL"
export const HIDE_ADVERTISEMENT_ADD_MODAL = "HIDE_ADVERTISEMENT_ADD_MODAL"

export const SHOW_GEOCODING_MODAL = "SHOW_GEOCODING_MODAL"
export const HIDE_GEOCODING_MODAL = "HIDE_GEOCODING_MODAL"

export const SHOW_SPECIAL_DETAIL_MODAL = "SHOW_SPECIAL_DETAIL_MODAL"
export const HIDE_SPECIAL_DETAIL_MODAL = "HIDE_SPECIAL_DETAIL_MODAL"

export const SHOW_COUPON_DETAIL_MODAL = "SHOW_COUPON_DETAIL_MODAL"
export const HIDE_COUPON_DETAIL_MODAL = "HIDE_COUPON_DETAIL_MODAL"
