export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE = "LOG_IN_FAILURE"

export const CHECK_LOGGED_REQUEST = "CHECK_LOGGED_REQUEST"
export const CHECK_LOGGED_SUCCESS = "CHECK_LOGGED_SUCCESS"
export const CHECK_LOGGED_FAILURE = "CHECK_LOGGED_FAILURE"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const CHANGE_IS_REGISTERED = "CHANGE_IS_REGISTERED"

export const LOG_OUT = "LOG_OUT"

export const LOAD_MY_STORES_REQUEST = "LOAD_STORES_REQUEST"
export const LOAD_MY_STORES_SUCCESS = "LOAD_STORES_SUCCESS"
export const LOAD_MY_STORES_FAILURE = "LOAD_STORES_FAILURE"

export const UPDATE_OWNER_INFO_REQUEST = "UPDATE_OWNER_INFO_REQUEST"
export const UPDATE_OWNER_INFO_SUCCESS = "UPDATE_OWNER_INFO_SUCCESS"
export const UPDATE_OWNER_INFO_FAILURE = "UPDATE_OWNER_INFO_FAILURE"
export const CHANGE_IS_UPDATED_OWNER_INFO = "CHANGE_IS_UPDATED_OWNER_INFO"

export const UPDATE_OWNER_PASSWORD_REQUEST = "UPDATE_OWNER_PASSWORD_REQUEST"
export const UPDATE_OWNER_PASSWORD_SUCCESS = "UPDATE_OWNER_PASSWORD_SUCCESS"
export const UPDATE_OWNER_PASSWORD_FAILURE = "UPDATE_OWNER_PASSWORD_FAILURE"
export const CHANGE_IS_UPDATED_OWNER_PASSWORD =
    "CHANGE_IS_UPDATED_OWNER_PASSWORD"

export const LOAD_OWNER_INFO_REQUEST = "LOAD_OWNER_INFO_REQUEST"
export const LOAD_OWNER_INFO_SUCCESS = "LOAD_OWNER_INFO_SUCCESS"
export const LOAD_OWNER_INFO_FAILURE = "LOAD_OWNER_INFO_FAILURE"
