export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS"
export const LOG_IN_FAILURE = "LOG_IN_FAILURE"

export const CHECK_LOGGED_REQUEST = "CHECK_LOGGED_REQUEST"
export const CHECK_LOGGED_SUCCESS = "CHECK_LOGGED_SUCCESS"
export const CHECK_LOGGED_FAILURE = "CHECK_LOGGED_FAILURE"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

export const LOG_OUT = "LOG_OUT"

export const GET_MY_STORE_LIST_REQUEST = "GET_MY_STORE_LIST_REQUEST"
export const GET_MY_STORE_LIST_SUCCESS = "GET_MY_STORE_LIST_SUCCESS"
export const GET_MY_STORE_LIST_FAILURE = "GET_MY_STORE_LIST_FAILURE"
