export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST"
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS"
export const ADD_STORE_FAILURE = "ADD_STORE_FAILURE"
export const CHANGE_STORE_ADDED = "CHANGE_STORE_ADDED"
