export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST"
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS"
export const ADD_STORE_FAILURE = "ADD_STORE_FAILURE"
export const CHANGE_STORE_ADDED = "CHANGE_STORE_ADDED"

export const LOAD_STORE_REQUEST = "LOAD_STORE_REQUEST"
export const LOAD_STORE_SUCCESS = "LOAD_STORE_SUCCESS"
export const LOAD_STORE_FAILURE = "LOAD_STORE_FAILURE"

export const ADD_BIZ_REG_IMG_REQUEST = "ADD_BIZ_REG_IMG_REQUEST"
export const ADD_BIZ_REG_IMG_SUCCESS = "ADD_BIZ_REG_IMG_SUCCESS"
export const ADD_BIZ_REG_IMG_FAILURE = "ADD_BIZ_REG_IMG_FAILURE"
export const CHANGE_ADDED_BIZ_REG_IMG = "CHANGE_ADDED_BIZ_REG_IMG"

export const LOAD_STORE_ADVERTISEMENTS_REQUEST =
    "LOAD_STORE_ADVERTISEMENTS_REQUEST"
export const LOAD_STORE_ADVERTISEMENTS_SUCCESS =
    "LOAD_STORE_ADVERTISEMENTS_SUCCESS"
export const LOAD_STORE_ADVERTISEMENTS_FAILURE =
    "LOAD_STORE_ADVERTISEMENTS_FAILURE"

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST"
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS"
export const UPDATE_STORE_FAILURE = "UPDATE_STORE_FAILURE"
export const CHANGE_STORE_UPDATED = "CHANGE_STORE_UPDATED"

export const REMOVE_STORE_REQUEST = "REMOVE_STORE_REQUEST"
export const REMOVE_STORE_SUCCESS = "REMOVE_STORE_SUCCESS"
export const REMOVE_STORE_FAILURE = "REMOVE_STORE_FAILURE"
export const CHANGE_STORE_REMOVED = "CHANGE_STORE_REMOVED"

export const CHANGE_ADDRESS = "CHANGE_ADDRESS"
export const CHANGE_LAT = "CHANGE_LAT"
export const CHANGE_LNG = "CHANGE_LNG"

export const LOAD_MAPS_GEOCODING_REQUEST = "LOAD_MAP_GEOCODING_REQUEST"
export const LOAD_MAPS_GEOCODING_SUCCESS = "LOAD_MAP_GEOCODING_SUCCESS"
export const LOAD_MAPS_GEOCODING_FAILURE = "LOAD_MAP_GEOCODING_FAILURE"
