export const ADD_STORE_REQUEST = "ADD_STORE_REQUEST"
export const ADD_STORE_SUCCESS = "ADD_STORE_SUCCESS"
export const ADD_STORE_FAILURE = "ADD_STORE_FAILURE"
export const CHANGE_STORE_ADDED = "CHANGE_STORE_ADDED"

export const LOAD_STORE_REQUEST = "LOAD_STORE_REQUEST"
export const LOAD_STORE_SUCCESS = "LOAD_STORE_SUCCESS"
export const LOAD_STORE_FAILURE = "LOAD_STORE_FAILURE"

export const ADD_BIZ_REG_IMG_REQUEST = "ADD_BIZ_REG_IMG_REQUEST"
export const ADD_BIZ_REG_IMG_SUCCESS = "ADD_BIZ_REG_IMG_SUCCESS"
export const ADD_BIZ_REG_IMG_FAILURE = "ADD_BIZ_REG_IMG_FAILURE"
export const CHANGE_ADDED_BIZ_REG_IMG = "CHANGE_ADDED_BIZ_REG_IMG"
